export enum ENUM_COMPANY_STATUS_CODE_ERROR {
    COMPANY_NOT_FOUND_ERROR = 5200,
    COMPANY_EXIST_ERROR = 5201,
    COMPANY_IS_ACTIVE_ERROR = 5204,
    COMPANY_INACTIVE_ERROR = 5205,
    COMPANY_INACTIVE_PERMANENT_ERROR = 5206,
    COMPANY_BLOCKED_ERROR = 5211,
}
