version: '3.8'
services:
  service:
    build: .
    container_name: service
    hostname: service
    ports:
      - 3333:3333
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: unless-stopped
networks:
  app-network:
    name: app-network
    driver: bridge