export enum ENUM_DRIVER_STATUS_CODE_ERROR {
    DRIVER_NOT_FOUND_ERROR = 5200,
    DRIVER_EXIST_ERROR = 5201,
    DRIVER_IS_ACTIVE_ERROR = 5204,
    DRIVER_INACTIVE_ERROR = 5205,
    DRIVER_INACTIVE_PERMANENT_ERROR = 5206,
    DRIVER_BLOCKED_ERROR = 5211,
}
